/*******************************************************************************
 * Copyright (c) The JETSCAPE Collaboration, 2018
 *
 * Modular, task-based framework for simulating all aspects of heavy-ion collisions
 *
 * For the list of contributors see AUTHORS.
 *
 * Report issues at https://github.com/JETSCAPE/JETSCAPE/issues
 *
 * or via email to bugs.jetscape@gmail.com
 *
 * Distributed under the GNU General Public License 3.0 (GPLv3 or later).
 * See COPYING for details.
 ******************************************************************************/
// -----------------------------------------------------------------------------
// This is a wrapper for SMASH hadronic transport with the JETSCAPE framework
// for to create a nucleus at rest
// -----------------------------------------------------------------------------

#ifndef SMASHNUCLEUSWRAPPER_H
#define SMASHNUCLEUSWRAPPER_H

// Forward declare to_string for PdgCode so SMASH's YAML conversion sees it
#include <string>
namespace smash {
class PdgCode;
std::string to_string(const PdgCode &code);
}

#include "smash/configuration.h"
#include "smash/collidermodus.h"
#include "smash/experiment.h"

#include "JetScapeModuleBase.h"
#include "JetScapeLogger.h"

namespace Jetscape {

/**
 * @class NucleusModus
 * @brief Handles the configuration and initialization of nuclei.
 */
class NucleusModus : public smash::ColliderModus {
public:
  /**
    * @brief Constructor for NucleusModus.
    * @param modus_config1 The primary configuration for the ColliderModus base class.
    * @param modus_config2 The secondary configuration used for initialization of the nucleus.
    */
  explicit NucleusModus(smash::Configuration modus_config1,
                        smash::Configuration modus_config2)
      : smash::ColliderModus(std::move(modus_config1),
                             create_default_experiment_parameters()) {
    initialize_projectile(modus_config2);
    modus_config1.clear();
  }

  /**
    * @brief Generates the initial conditions for the nucleus.
    * @param particles Pointer to the particles to populate.
    */
  void initial_conditions(smash::Particles *particles) {
    // Populate the nuclei with appropriately distributed nucleons
    projectile_->arrange_nucleons();
    projectile_->generate_fermi_momenta();
    // Put the particles in the nuclei into code particles
    projectile_->copy_particles(particles);
  }

private:
  /**
    * @brief Initializes the projectile nucleus from a configuration.
    * @param modus_config The configuration for the projectile nucleus.
    */
  void initialize_projectile(smash::Configuration &modus_config) {
    // Mirror SMASH collidermodus: extract full-labeled sections and then
    // pass the Projectile sub-config to Nucleus.
    smash::Configuration modus_cfg =
        modus_config.extract_complete_sub_configuration(
            smash::InputSections::m_collider);
    smash::Configuration proj_cfg =
        modus_cfg.extract_complete_sub_configuration(
            smash::InputSections::m_c_projectile);

    // Construct projectile nucleus
    projectile_ = std::make_unique<smash::Nucleus>(proj_cfg, 1);

    // Ensure no unused keys remain to avoid destructor exceptions
    proj_cfg.clear();
    modus_cfg.clear();
    modus_config.clear();
  }

  /**
    * @brief Creates default experiment parameters for the nucleus.
    * @return Default experiment parameters.
    */
  static smash::ExperimentParameters create_default_experiment_parameters() {
    smash::ExperimentParameters params{};
    params.testparticles = 1;
    return params;
  }

  /// The unique pointer to the projectile nucleus.
  std::unique_ptr<smash::Nucleus> projectile_;
};

/**
 * @class SMASHNucleusWrapper
 * @brief A wrapper class for integrating SMASH nuclei with JetScape.
 */
class SMASHNucleusWrapper : public JetScapeModuleBase {
private:
  /// Indicates whether Fermi momenta are applied.
  bool Fermi_momenta_;
  /// The mass of a nucleon in GeV.
  const double nucleon_mass_ = 0.938;
  /// The radius of the nucleus in fm.
  double nucleon_radius_black_disk_;

  /// Shared pointer to the NucleusModus instance.
  shared_ptr<NucleusModus> smash_nucleus_;

  /// Static registration of the module in the Jetscape framework.
  static RegisterJetScapeModule<SMASHNucleusWrapper> reg;

  /// Pointer to store the hadrons generated by the nucleus.
  smash::Particles *smash_nucleus_hadrons_;

  /// Hadrons generated by the nucleus.
  std::vector<Hadron> hadrons_;

public:
  /**
    * @brief Default constructor.
    */
  SMASHNucleusWrapper();

  /**
    * @brief Destructor.
    */
  ~SMASHNucleusWrapper();

  /**
    * @brief Initializes the SMASH nucleus wrapper module.
    */
  void InitTask();

  /**
    * @brief Executes the task of generating nuclei.
    */
  void ExecuteTask();

  /**
   * @brief Stores the hadrons generated by the nucleus in the wrapper.
   * This function iterates through the particles in the SMASH nucleus
   * and creates Hadron objects for each particle, storing them in the hadrons_ 
   * vector.
   */
  void StoreHadronsInWrapper();

  /**
    * @brief Retrieves the current list of generated hadrons.
    * @return A vector containing the current list of hadrons.
    */
  std::vector<Hadron> GetCurrentHadronList() const;

  /**
    * @brief Retrieves the history of the current module.
    * @return The history of generated hadrons as a generic type.
    */
  virtual any GetHistory() { return GetCurrentHadronList(); }

  /** 
   * @brief Checks if a Hadron is at a specific position.
   * @param t The time at which to check the position.
   * @param x The x coordinate of the position.
   * @param y The y coordinate of the position.
   * @param z The z coordinate of the position.
   * @return True if a Hadron is at the specified position, false otherwise.
   * 
   * @note When a boost is applied the times are different from 0, which is the 
   * default time of the hadrons in the nucleus.
   * This function checks if any hadron is at the specified position at the 
   * given time within a small tolerance.
   * The tolerance is set to rounding_error.
   */
  bool IsHadronAtPosition(double t, double x, double y, double z) const;

  /**
   * @brief Boost the hadrons in the nucleus with a given velocity.
   * @param vx The x component of the boost velocity.
   * @param vy The y component of the boost velocity.
   * @param vz The z component of the boost velocity.
   * @return A vector of Hadron objects that have been boosted.
   * 
   * @note This function modifies the positions and momenta of the hadrons stored
   * in the hadrons_ vector by applying a Lorentz boost based on the provided
   * velocity components (vx, vy, vz) permanently.
   */
  std::vector<Hadron> GetCurrentHadronListBoosted(double vx, double vy, double vz);

  /**
   * @brief Boost function for (x0, x1, x2, x3) coordinates.
   * @param x0 The time coordinate.
   * @param x1 The x coordinate.
   * @param x2 The y coordinate.
   * @param x3 The z coordinate.
   * @param vx The x component of the boost velocity.
   * @param vy The y component of the boost velocity.
   * @param vz The z component of the boost velocity.
   * @return A tuple containing the boosted coordinates (x0', x1', x2', x3').
   */
  std::tuple<double, double, double, double> BoostCoordinates(double x0, double x1, double x2, double x3, double vx, double vy, double vz) const;

};

} // end namespace Jetscape

#endif // SMASHNUCLEUSWRAPPER_H