/*******************************************************************************
 * Copyright (c) The JETSCAPE Collaboration, 2018
 *
 * Modular, task-based framework for simulating all aspects of heavy-ion
 *collisions
 *
 * For the list of contributors see AUTHORS.
 *
 * Report issues at https://github.com/JETSCAPE/JETSCAPE/issues
 *
 * or via email to bugs.jetscape@gmail.com
 *
 * Distributed under the GNU General Public License 3.0 (GPLv3 or later).
 * See COPYING for details.
 ******************************************************************************/

#ifndef JETSCAPEDATAPATH_H
#define JETSCAPEDATAPATH_H

#include <cstdlib>
#include <string>

// XscapeInstallPaths.h is generated by CMake and defines XSCAPE_INSTALL_DATADIR.
// It is only present in configured builds; guard against its absence so the
// header remains usable in plain-compilation scenarios (e.g. unit tests that
// compile files directly without CMake).
#if __has_include("XscapeInstallPaths.h")
#  include "XscapeInstallPaths.h"
#endif
#ifndef XSCAPE_INSTALL_DATADIR
#  define XSCAPE_INSTALL_DATADIR "."
#endif

namespace Jetscape {

// Root directory holding X-SCAPE read-only data assets (EOS tables, iSS tables,
// LBT tables, 3dMCGlauber inputs, ...). Priority:
//   1. XSCAPE_DATA_DIR environment variable (runtime override)
//   2. XSCAPE_INSTALL_DATADIR baked in at configure time (installed prefix)
//   3. "." (current working directory) — preserves historical build-dir behavior
inline std::string GetXSCAPEDataDir() {
  const char *env = std::getenv("XSCAPE_DATA_DIR");
  if (env != nullptr && env[0] != '\0') {
    return std::string(env);
  }
  // Use the baked install-time path if it is a real absolute directory.
  // This makes an installed runJetscape work out-of-the-box without setting
  // any environment variables.
  const std::string baked(XSCAPE_INSTALL_DATADIR);
  if (!baked.empty() && baked != "." && baked[0] == '/') {
    return baked;
  }
  return std::string(".");
}

// Resolve a relative data-asset path against GetXSCAPEDataDir(). An absolute
// path (leading '/') is returned unchanged.
inline std::string XSCAPEDataPath(const std::string &relative_path) {
  if (!relative_path.empty() && relative_path[0] == '/') {
    return relative_path;
  }
  return GetXSCAPEDataDir() + "/" + relative_path;
}

}  // namespace Jetscape

#endif  // JETSCAPEDATAPATH_H
