name: docker-build

on:
  push:
    branches:
      - latessa/dockerImage

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.XSCAPE_DOCKER_USERNAME }}
          password: ${{ secrets.XSCAPE_DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push 
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile.base
          push: true
          tags: ${{ secrets.XSCAPE_DOCKER_USERNAME }}/base:v1.8

