name: plot observables

on:
  push:
    branches:
      - main
      - latessa/automatedTests

env:
  PULL_NUMBER: ${{ github.event.number }}

jobs:
  build:
    name: Run_Plot_Test
    runs-on: ubuntu-latest
    
    container:
      image: jetscape/base:stable
      options: --user root
      
    steps:
      
    - name: Checkout X-SCAPE-COMP
      uses: actions/checkout@v2
      with:
        path: X-SCAPE-COMP
      
    - name: Build JETSCAPE
      run: |
        cd $GITHUB_WORKSPACE/X-SCAPE-COMP
        mkdir build
        cd build
        cmake ..
        make -j2

    - name: Generate pp events
      run: |
        cd $GITHUB_WORKSPACE/X-SCAPE-COMP/build
        $GITHUB_WORKSPACE/X-SCAPE-COMP/build/runJetscape $GITHUB_WORKSPACE/X-SCAPE-COMP/test/pp/config/jetscape_user_PP19_weighted.xml $GITHUB_WORKSPACE/X-SCAPE-COMP/config/jetscape_main.xml

    - name: Plot observables
      run: |
        echo $PULL_NUMBER
        $GITHUB_WORKSPACE/X-SCAPE-COMP/test/generate_plots.sh -j $GITHUB_WORKSPACE/X-SCAPE-COMP -o $GITHUB_WORKSPACE/X-SCAPE-COMP/test/plot/output/new

    - name: Prepare TAR file for transfer
      run: |
        export ET=`date "+%Y%m%d%H%M%S"`
        mkdir /__w/X-SCAPE-COMP/X-SCAPE-COMP/X-SCAPE-COMP/test/plot/output/archive
        cd /__w/X-SCAPE-COMP/X-SCAPE-COMP/X-SCAPE-COMP/test/plot/output/new
        tar -cvzf /__w/X-SCAPE-COMP/X-SCAPE-COMP/X-SCAPE-COMP/test/plot/output/archive/files_$ET.tar.gz .
        cd /__w/X-SCAPE-COMP/X-SCAPE-COMP/X-SCAPE-COMP/test/plot/output/archive
        echo "pwd of archive"
        pwd
        echo "ls of archive"
        ls

    - name: Deploy Plots
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: "ftp.joelatessa.com"
        user: "jetscapeTest@plot.joelatessa.com"
        password: ${{ secrets.JETSCAPE_FTP_PASS }}
        local_dir: "./X-SCAPE-COMP/test/plot/output/archive"
        remote_dir: "./"
        delete: "false"
