name: smash test completes

on:
  pull_request:
    branches:
      - main
      - XSCAPE-1.2-RC

  push:
    branches:
      - main
      - XSCAPE-1.2-RC

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: build for smash test
    runs-on: ubuntu-latest

    container:
      image: jetscape/base:v1.11
      options: --user root
    
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Download MUSIC
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/external_packages
        ./get_music.sh

    - name: Download ISS
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/external_packages
        ./get_iSS.sh

    - name: Download FREESTREAM
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/external_packages
        ./get_freestream-milne.sh

    - name: Download SMASH
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/external_packages
        ./get_smash.sh

    - name: Build Application
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}
        mkdir build
        cd build
        export SMASH_DIR="${GITHUB_WORKSPACE}/${REPO_NAME}/external_packages/smash/smash_code"
        cmake .. -DUSE_MUSIC=ON -DUSE_ISS=ON -DUSE_FREESTREAM=ON -DUSE_SMASH=ON
        make -j6

    - name: Run Application
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/build
        ./runJetscape ../config/jetscape_user_test_smash_RC1_1.xml
