name: build+regression test pp

on:
  pull_request:
    branches:
      - main
      - XSCAPE-1.1.1-RC
      - XSCAPE-1.1-RC_mergeMUSIC

  push:
    branches:
      - main
      - XSCAPE-1.1.1-RC
      - XSCAPE-1.1-RC_mergeMUSIC

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: pp+PbPb
    runs-on: ubuntu-latest

    container:
      image: jetscape/base:stable
      options: --user root

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Build Application
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}
        mkdir build
        cd build
        cmake ..
        make -j2

    - name: Checkout TEST-EXAMPLES
      uses: actions/checkout@v4
      with:
        repository: JETSCAPE/TEST-EXAMPLES
        ref: jetscape-3.6.1-rc
        path: TEST-EXAMPLES

    - name: Run pp tests
      run: ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/runTest.sh -j ${GITHUB_WORKSPACE}/${REPO_NAME} -a ${GITHUB_WORKSPACE}/TEST-EXAMPLES -c ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/pp/config/jetscapeTestConfig.yaml -o ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/pp/output/new -r ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/pp/output/latest
