name: build+regression test

on:
  pull_request:
    branches:
      - main
      - latessa/automatedTests
  push:
    branches:
      - main
      - latessa/automatedTests

jobs:
  build:
    name: pp+PbPb
    runs-on: ubuntu-latest

    container:
      image: jetscape/base:stable
      options: --user root

    steps:

    - name: Checkout X-SCAPE-COMP
      uses: actions/checkout@v2
      with:
        path: X-SCAPE-COMP

    - name: Build X-SCAPE-COMP
      run: |
        cd $GITHUB_WORKSPACE/X-SCAPE-COMP
        mkdir build
        cd build
        cmake ..
        make -j2

    - name: Run pp tests
      run: $GITHUB_WORKSPACE/X-SCAPE-COMP/test/runTest.sh -j $GITHUB_WORKSPACE/X-SCAPE-COMP -c $GITHUB_WORKSPACE/X-SCAPE-COMP/test/pp/config/jetscapeTestConfig.yaml -o $GITHUB_WORKSPACE/X-SCAPE-COMP/test/pp/output/new -r $GITHUB_WORKSPACE/X-SCAPE-COMP/test/pp/output/latest

    - name: Run Pb-Pb tests
      run: $GITHUB_WORKSPACE/X-SCAPE-COMP/test/runTest.sh -j $GITHUB_WORKSPACE/X-SCAPE-COMP -c $GITHUB_WORKSPACE/X-SCAPE-COMP/test/PbPb/config/jetscapeTestConfig.yaml -o $GITHUB_WORKSPACE/X-SCAPE-COMP/test/PbPb/output/new -r $GITHUB_WORKSPACE/X-SCAPE-COMP/test/PbPb/output/latest
