name: build+regression test Pythia-ISR Parton Output

on:
  pull_request:
    branches:
      - main
      - XSCAPE-RC2
      - XSCAPE-0.9.1-for-public-repo
      - XSCAPE-RC2

  push:
    branches:
      - main
      - XSCAPE-RC2
      - XSCAPE-0.9.1-for-public-repo

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: Pythia-ISR-TEST Parton File
    runs-on: ubuntu-latest

    container:
      image: jetscape/base:v1.8
      options: --user root

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}

    - name: Download 3DGlauber
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/external_packages
        ./get_3dglauber.sh
        ./get_music.sh
        ./get_iSS.sh

    - name: Build Application
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_STANDARD=14 -DUSE_3DGlauber=ON -DUSE_MUSIC=ON -DUSE_ISS=ON
        make -j2

    - name: Checkout TEST-EXAMPLES
      uses: actions/checkout@v2
      with:
        repository: JETSCAPE/TEST-EXAMPLES
        path: TEST-EXAMPLES

    - name: Run Pythia ISR Parton File Tests
      run: |
        export PYTHIA8="${PYTHIA8DIR}"
        ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/isr/runPythiaIsrPartonTest.sh -j ${GITHUB_WORKSPACE}/${REPO_NAME} -a ${GITHUB_WORKSPACE}/TEST-EXAMPLES -c ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/isr/config/jetscape_user_iMATTERMCGlauber.xml -o ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/isr/output/new -r ${GITHUB_WORKSPACE}/TEST-EXAMPLES/test/isr/output/latest
