name: build+regression test

on:
  pull_request:
    branches:
      - main
      - latessa/automatedTests
  push:
    branches:
      - main
      - latessa/automatedTests

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: pp+PbPb
    runs-on: ubuntu-latest
    
    container:
      image: jetscape/base:stable
      options: --user root
      
    steps:
      
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}
      
    - name: Build Application
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}
        mkdir build
        cd build
        cmake ..
        make -j2
      
    - name: Run pp tests
      run: ${GITHUB_WORKSPACE}/${REPO_NAME}/test/runTest.sh -j ${GITHUB_WORKSPACE}/${REPO_NAME} -c ${GITHUB_WORKSPACE}/${REPO_NAME}/test/pp/config/jetscapeTestConfig.yaml -o ${GITHUB_WORKSPACE}/${REPO_NAME}/test/pp/output/new -r ${GITHUB_WORKSPACE}/${REPO_NAME}/test/pp/output/latest
      
    - name: Run Pb-Pb tests
      run: ${GITHUB_WORKSPACE}/${REPO_NAME}/test/runTest.sh -j ${GITHUB_WORKSPACE}/${REPO_NAME} -c ${GITHUB_WORKSPACE}/${REPO_NAME}/test/PbPb/config/jetscapeTestConfig.yaml -o ${GITHUB_WORKSPACE}/${REPO_NAME}/test/PbPb/output/new -r ${GITHUB_WORKSPACE}/${REPO_NAME}/test/PbPb/output/latest
